added lesson 5
anatolytsi/basic_course_django_gb pull request #5
Opened 2021-03-09 22:09 UTC by anatolytsi

Вроде ничего не забыл, для этого урока пришлось много погуглить, особенно про загрузку аватара. В целом разобрался, но все равно вопросы остались, например, куда девать автогенерирующиеся Currently и Clear? Я следующий урок не смотрел, но наверняка там это будет. К сожалению времени нет в последние дни, сдать через 2 после лекции пока нет возможности, но стараюсь в срок!

2021-03-11 09:34 UTC, Vokler requested changes

2021-03-11 09:34 UTC, Vokler commented on authapp/forms.py
> +        self.fields["avatar"].widget.attrs["class"] = "form-control py-4 custom-file-input"
Для поля avatar достаточно только `custom-file-input`

2021-03-11 09:34 UTC, Vokler commented on authapp/views.py
> +        "baskets": Basket.objects.all(),
Здесь будет небольшой баг с тем, что если вы добавите товары в корзину через одного пользователя, а потом зайдете через другого, у 2го будут те же товары в корзине лежать, что и у первого. Нужно пофиксить этот момент

2021-03-11 17:45 UTC, anatolytsi commented on authapp/views.py
> +        "baskets": Basket.objects.all(),
Пофиксил!

2021-03-11 17:45 UTC, anatolytsi commented on authapp/forms.py
> +        self.fields["avatar"].widget.attrs["class"] = "form-control py-4 custom-file-input"
Проблема с Currently и Change не решилась :(

2021-03-12 09:25 UTC, Vokler commented on authapp/forms.py
> +        self.fields["avatar"].widget.attrs["class"] = "form-control py-4 custom-file-input"
Посмотрите 5ый урок, когда мы добавляли виджет для `avatar`: `avatar = forms.ImageField(widget=forms.FileInput())`

2021-03-12 09:25 UTC, Vokler approved these changes

2021-03-12 09:25 UTC, merged